version: "3.9"
services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "8080:80" 